services:
  nginx:
    container_name: loan_nginx
    restart: unless-stopped
    build:
      context: environment/nginx
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ${LOAN_APP_DIR}:/var/www/app:cached
    links:
      - php

  php:
    container_name: loan_php
    restart: unless-stopped
    build:
      context: environment/php
    ports:
      - "${PHP_PORT}:9000"
    volumes:
      - ${LOAN_APP_DIR}:/var/www/app:cached

  postgres:
    container_name: loan_postgres
    restart: unless-stopped
    image: postgres:17.0
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data

networks:
  loans_network:
    driver: bridge
